### ISSUE TITLE
Add CI and Code Coverage

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/java-multibase#3]
Should this project, along with java-multiaddr and java-multihash, have CI and Code Coverage? I don't know much about how to do this for java projects. Is it straightforward?

**Comment by RichardLitt** [comment]
Ah, looks like java-multihash has Travis enabled. Should we do that for this repo, too?

**Comment by ianopolous** [comment]
Yep, I haven't hooked up travis yet, but it's just a matter of running "ant test"

**Comment by RichardLitt** [comment]
Sweet. Would be great to add a travis badge and hook this up. :)
