### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by mk868** [multiformats/java-multibase#31]
Hello,
I have a question, can we make a new release of the `java-multibase` library?
The latest changes include support for Java modules and have begun to be critical for me

I can provide support if needed

**Comment by ianopolous** [comment]
v1.2.0 is up

**Comment by mk868** [comment]
Thank you @ianopolous,  
Unfortunately jitpack compilation failed, could you please look at this https://github.com/multiformats/java-multibase/pull/33?
If you choose to merge the changes you just need to re-create the tag on github and the compilation should succeed
