### ISSUE TITLE
Managing versions of Java multiformats on Maven

### ISSUE THREAD

**Issue by sic2** [multiformats/java-multibase#6]
Hi,

How often do you update the versions for the Java multiformats on Jitpack?
I am trying to use the latest version of java-multibase for the java-multiaddr, but I am unable to do so.

Alternatively, how can I force java-multiaddr or java-multihash to use my local version of the java-multibase? 

Cheers!

**Comment by ianopolous** [comment]
I don't personally use maven. But I can do a release whenever appropriate. I'll try to find time this weekend.

**Comment by sic2** [comment]
Okay. No rush. I will try to understand how to manage the versions locally meanwhile.
