### ISSUE TITLE
Release multibase to maven central

### ISSUE THREAD

**Issue by tdiesler** [multiformats/java-multibase#7]
The build of dependent projects rely on this to be found on central or some other mvn repository. I can provide a PR that would allow to run 

```
mvn release:prepare
```

I could then use the created tag to deploy it to central. Better still, someone else with appropriate authorization could run 

```
mvn release:perform
```

Here is the PR: https://github.com/multiformats/java-multibase/pull/8

**Comment by ianopolous** [comment]
I don't use maven, but my understand is that this is published to jitpack.io. Are you able to use that?

**Comment by tdiesler** [comment]
Yes, jitpack works fine - I was not aware of that.
